### ISSUE TITLE
connect to spotify connect device via HA

### ISSUE THREAD

**Issue by marcianito** [giannello/addon-spotify-connect#13]
Dear community,

I came across this repo after searching how to do the following:

1) I have (several) spotify premium accounts
2) I have a raspberry py (connected to physical music speakers) running a spotify connect instance
3) home assistant with working spotify and spotcast integration + spotify connect add-on

The problem (or what I hoped for):

1) working case: I can use my cell to pick music and parse it to the spotify connect instance, music will then play just fine
I now want to do the same BUT via my home assistant (where I use a different account as on my cell)
2) also working in HA:
- spotify registered and working with desired account
- spotcast registered with desired account

2) I cannot select the desired device (my spotify connect device name). It is just not shown in HA (web browser).
3) I tried using "spotify-card". It shows my playlists but NOT the spotify connect device
4) also via add-on "configuration" it is not possible to set up the output (or input) device. 

Is thee anyone with a working example or another work-around to get this scenario to function?

Any help would be highly appreciated!!!

Best regards,

Marvin

**Comment by giannello** [comment]
Hi @marcianito 

This repository is only a fork of the official Spotify Add-on with some added features. The scenario you describe can not be solved by this integration. For support, please head over to the [Home Assistant forum](https://community.home-assistant.io/)
